-- =============================================================================
-- OnlineOrder — V2__add_orders_status.sql
-- 为 orders 表增加状态字段，支持订单状态机
--
-- 执行时机：V1 迁移完成后执行
-- =============================================================================

-- orders 表已包含 status 字段（在 V1__initial_schema.sql 中定义），
-- 此迁移文件用于记录状态机的业务规则。
--
-- 订单状态流转：
--   PENDING (待支付) → CONFIRMED (已确认) → PREPARING (制作中)
--                 → SHIPPING (配送中) → COMPLETED (已完成)
--   任意状态 → CANCELLED (已取消)
--
-- 说明：
--   此迁移脚本仅用于文档目的。
--   实际的状态值已在 V1__initial_schema.sql 中通过 DEFAULT 'PENDING' 设置。
--   如需添加状态约束，可在下方 UNLOGGED 表或注释中添加 CHECK 约束。
